project:
  type: website

website:
  title: "Hist 5454 - Spring 2024"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    pinned: true
    contents:
      - section: "Schedule"
        contents:
          - href: meetings/01-intro.qmd
            text: 1. Introduction
          - href: meetings/02-dh-and-ph.qmd
            text: 2. Digital History and Public History
      - href: resources.qmd
        text: Resources
      - href: faq.qmd
        text: FAQ

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Jesse Sadler"
    background: "#861F41" # Chicago Maroon

format:
  html:
    theme:
      light: [default, styles.scss]
      dark: [darkly, styles.scss]
    mainfont: "Nunito Sans"
    toc: true
    code-copy: true



