project:
  type: website

website:
  page-navigation: true
  favicon: logo.png
  site-url: https://jessesadler.github.io/vt5454-s24/
  repo-url: https://github.com/jessesadler/vt5454-s24
  repo-actions: [edit,issue]

  sidebar:
    logo: logo.png
    style: docked
    search: true
    pinned: true
    align: center
    tools:
      - icon: house-fill
        href: index.qmd
      - icon: github
        href: https://github.com/jessesadler/vt5454-s24
    contents:
      - section: "Schedule"
        contents:
          - href: meetings/01-intro.qmd
            text: 1. Introduction
          - href: meetings/02-dh-and-ph.qmd
            text: 2. Digital History and Public History
          - href: meetings/03-organization.qmd
            text: 3. Organizing resources
          - href: meetings/04-markdown.qmd
            text: 4. Plain text and markdown
          - href: meetings/05-data.qmd
            text: 5. Data and an intro to the command line
          - href: meetings/06-rstats.qmd
            text: 6. Intro to R and RStudio
          - href: meetings/07-wrangle.qmd
            text: 7. Data wrangling
          - href: meetings/08-ggplot2.qmd
            text: 8. Visualization with ggplot2
          - href: meetings/09-git.qmd
            text: 9. Version control with Git and GitHub
          - href: meetings/10-quarto.qmd
            text: 10. Making documents and websites with Quarto
          - href: meetings/11-review.qmd
            text: 11. Review and website workshop
          - href: meetings/12-spatial.qmd
            text: 12. Spatial analysis
          - href: meetings/13-network.qmd
            text: 13. Network analysis
          - href: meetings/14-design.qmd
            text: 14. Web design and visualization
          - href: meetings/16-text.qmd
            text: "Appendix: Text analysis"
      - section: "Guides"
        contents:
          - href: guides/zotero.qmd
          - href: guides/plaintext.qmd
          - href: guides/markdown-syntax.qmd
          - href: guides/geo-data.qmd
      - href: resources.qmd
      - href: faq.qmd
      - href: computing.qmd

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Jesse Sadler"
    background: "#861F41" # Chicago Maroon

format:
  html:
    theme:
      light: [default, styles.scss]
      dark: [darkly, styles.scss]
    mainfont: "Nunito Sans"
    toc: true
    code-copy: true



