---
title: "Computing"
---


## Command line terminal {#sec-cl}

### macOS
macOS is built on the foundation of [Unix](https://en.wikipedia.org/wiki/Unix) and comes with a perfectly capable command line app in Terminal. There are some other options out there, but Terminal is just fine.

Since 2019 the default shell in macOS is [zsh](https://en.wikipedia.org/wiki/Z_shell) instead of [bash](https://www.gnu.org/software/bash/). The differences between zsh and bash should not affect beginners too much. However, you can download an updated version of bash. The best way to do this is with [Homebrew](https://brew.sh).

[Homebrew](https://brew.sh) is one of the main ways to install command line packages on macOS such as Git, and so it is a good idea to install it. Read about how to install Homebrew through the Terminal app on the [Homebrew's homepage](https://brew.sh).

### Windows
Windows does not come with a unix shell installed. You can install one via [Git Bash](https://gitforwindows.org). This will install both the bash shell and git. See the [Carpentries](https://carpentries.github.io/workshop-template/install_instructions/#the-bash-shell) for installation instructions.

## Git {#sec-git}
See [Happy Git and GitHub for the useR](https://happygitwithr.com/install-git) for a good guide to downloading git for macOS and Windows.

### macOS
Git may already be on your computer by default, but the git version that comes with macOS can be quite out of date. To check if you need to install git:

1. Open Terminal
2. Type `git --version` – check current version of git on the computer
3. Look at current version of Git at https://git-scm.com

If you need to install Git, there are two basic ways to install it:

Via [Homebrew](https://brew.sh):

1. `brew install git` – download git with Homebrew
2. Quit terminal and reopen it to start new session
3. `git --version` – check to see that installation worked.

Via Xcode command line tools:

1. `xcode-select --install`
2. Quit terminal and reopen it to start new session
3. `git --version` – check to see that installation worked.

### Windows
Install git with [Git Bash](https://gitforwindows.org).

## GitHub {#sec-github}
Register for an account on [GitHub](https://github.com)

## R and RStudio {#sec-r}
- [Download R from CRAN](https://cloud.r-project.org). R 4.3.2 is currently the newest release. It is expected that you will have a version greater than or equal to 4.3.
- [Download RStudio](https://posit.co/download/rstudio-desktop/).
- [RStudio IDE User Guide](https://docs.posit.co/ide/user/)

## Quarto {#sec-quarto}
- The quarto R package is installed with the newer versions of RStudio. See the documentation on [using Quarto with RStudio](https://quarto.org/docs/tools/rstudio.html).
- Quarto can also be run from the command line, which is how we will publish our websites. You can download the Quarto command-line interface (CLI) in the [Get Stated](https://quarto.org/docs/get-started/) section of the Quarto website. Once you have downladed the CLI, you will be able to render and publish documents via the command line.
