---
title: "History 5454: Digital Humanities for Public History"
---

#### Spring 2024

::: columns
::: {.column width="50%"}
::: {.callout-note appearance="minimal"}
## Instructor
[Jesse Sadler](https://www.jessesadler.com). Email: <jrsadler@vt.edu>  
Office hours: Thursday, 1:00--2:00pm and by appointment in ...
:::
:::

::: {.column width="50%"}
::: {.callout-note appearance="minimal"}
## Course
History 5454: Spring 2024  
Meets Thursdays, 2:00–4:50 in Major Williams 427
:::
:::
:::

## Course description
This course is designed to introduce students to some of the tools of Digital Humanities/History with an emphasis on using open source technology that puts you in control. The course focuses on methodologies. It begins with the basics of organizing primary and secondary sources and your notes on them, to an introduction to data analysis and visualization using the R programming language, culminating in the creation of your own website. Along the way we will be learning the basics of using the command line and learn about git and using GitHub for publishing websites and to become acquainted with the practices of reproducible research.

::: {.callout-tip icon=false}
## Note
This course website will function as the main source of information for the course. The syllabus is liable to change based on new material and student input. Any changes will be made official on the website.
:::

## Learning goals
After taking this course, you will...

- have expanded awareness of the open source tools available for conducting historical research and making that research widely available to the public.
- be comfortable writing in plain text and using Markdown.
- understand the uses and drawbacks of spreadsheets and how to organize rectangular data.
- be comfortable with the basics of the command line.
- be able to import, explore, wrangle, and visualize data in R.
- be able to write R scripts and document your code in quarto documents.
- have familiarity with the tidyverse packages in R.
- have experience with the possibilities for text, network, and spatial analysis available through various R packages.
- be comfortable with using git and GitHub for your own work or collaboration with others.
- create a website using open source tools.

## Expectations
There are no prerequisites for this course. Students do not need to know anything about the methods and technologies listed in the syllabus. You do not need to know what the command line, R, or git is. That is what the course is for. Familiarity is, of course, helpful, and more advanced students can be accommodated within the structures of the course. However, the intention is for this to be an exploration of open source tools that can help you with historical analysis and publication. The primary expectation is a willingness to try and a readiness to learn. More specific expectations include:

- Complete and be ready to discuss all reading by our weekly meeting.
- Attendance and active participation in all seminars.
- Come to seminar with a computer ready to work and to participate in the weekly labs with all applications and programming environments installed by the assigned meeting.[^1]
- Complete all assignments on time.
- Complete the final project of creating a Quarto website.

Finally, it is expected that all students will be respectful of each other. Students will enter the course at different levels of comfort with the tools that we will use. The goal of the course is to help each other get more comfortable with open source technologies.

## Assessment
As noted above, the primary expectation for the course is a willingness to try, and so the primary assessment will be focused on effort and growth.

- Participation: 40%
- Weekly assignments: 20%
- Final project: 40%

## How the course works
Meetings will be divided between discussion of weekly readings and topics and interactive "labs" devoted to the tools and technologies for that week. All information necessary for the course is made available through this website. Information about weekly reading, assignments, and resources is available via the sidebar. This information is dynamic and liable to change, so please make sure to visit this website frequently.

::: {.callout-tip icon=false}
## Note
This website is built with [Quarto](https://quarto.org) and the source code is available on GitHub. If you want to see how anything works or to suggest any changes you can do so through GitHub.
:::

## Schedule

1. [Introduction][1] (18 January)
2. [Digital History and Public History][2] (25 January)
3. [Organizing resources][3] (1 February)
4. [Plain text and markdown][4] (8 February)
5. [Data and an intro to the command line][5] (15 February)
6. [Intro to R and RStudio][6] (22 February)
7. [Data wrangling][7] (29 February)
8. [Visualization with ggplot2][8] (14 March)
9. [Version control with Git and GitHub][9] (21 March)
10. [Making documents and websites with Quarto][10] (28 March)
11. [Text analysis][11] (4 April)
12. [Network analysis][12] (11 April)
13. [Spatial analysis][13] (18 April)
14. [Web design and visualization][14] (25 April)
15. [Conclusion][15] (2 May)


[^1]: If you have any problems, we can troubleshoot together.

[1]: meetings/01-intro.qmd
[2]: meetings/02-dh-and-ph.qmd
[3]: meetings/03-organization.qmd
[4]: meetings/04-markdown.qmd
[5]: meetings/05-data.qmd
[6]: meetings/06-rstats.qmd
[7]: meetings/07-wrangle.qmd
[8]: meetings/08-ggplot2.qmd
[9]: meetings/09-git.qmd
[10]: meetings/10-quarto.qmd
[11]: meetings/11-text.qmd
[12]: meetings/12-network.qmd
[13]: meetings/13-spatial.qmd
[14]: meetings/14-design.qmd
[15]: meetings/15-conclusion.qmd
