---
title: "Week 6: Intro to R and RStudio"
---


## Reading
- Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund, [*R for Data Science* (2nd Edition)](https://r4ds.hadley.nz): Introduction, Chapters 2, 4, 6, and  8.
- Kieran Healy, *Data Visualization: A Practical Introduction* (Princeton University Press, 2018), [Chapter 2: Get Started](https://socviz.co/gettingstarted.html#gettingstarted).

## Assignment
- Install [R](https://cloud.r-project.org) and [RStudio](https://posit.co/download/rstudio-desktop/). See [Computing R](/computing.qmd#sec-r).

## Activities
- Workshop: Intro to R
  - [R for Social Scientists: Intro to R](https://datacarpentry.org/r-socialsci/01-intro-to-r.html)
  - [RStudio IDE User Guide](https://docs.posit.co/ide/user/)
- Workshop: Importing data
  - [R for Social Scientists: Starting with data](https://datacarpentry.org/r-socialsci/02-starting-with-data.html)
  - [Download SAFI data](https://github.com/datacarpentry/r-socialsci/blob/main/episodes/data/SAFI_clean.csv)
  - [Download letters data](https://github.com/jessesadler/intro-to-r/blob/master/data/correspondence-data-1585.csv)
  - [Download readr example data](https://github.com/jessesadler/notes-tidyverse/blob/main/data/readr-example.csv)

## Resources
- [Data Carpentry - R for Social Scientists](https://datacarpentry.org/r-socialsci/)
- [Software Carpentry - R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/)
- Julie Lowndes and Allison Horst, [R for Excel Users: R & RStudio, RMarkdown](https://rstudio-conf-2020.github.io/r-for-excel/rstudio.html).
- [On importing data with readr](https://jessesadler.github.io/notes-tidyverse/01-readr.html)
