---
title: "Week 10: Making documents and websites with Quarto"
---


## Reading
- Look over the [Quarto documentation](https://quarto.org/docs/guide/).
- Anil Dash, [The Internet Is About to Get Weird Again](https://www.rollingstone.com/culture/culture-commentary/internet-future-about-to-get-weird-1234938403/), Rolling Stone (30 December 2023)

## Assignment
- Watch Mine Çetinkaya-Rundel and Julia Stewart Lowndes, [Hello Quarto: Share, Collaborate, Teach, Reimagine](https://youtu.be/p7Hxu4coDl8?si=CJH489eghcIF4hlr) at RStudio Conf 2022.
  - The slides are available [here](https://mine.quarto.pub/hello-quarto/).
- Plan out your website. Make an outline, mindmap, drawing, etc. of the structure of your website.

## Activities
- Discussion: Making History public through the web.
- Workshop: Making a website with Quarto

## Quarto websites
[Quarto websites](https://quarto.org/docs/websites/) are a collection of Quarto documents using `format: html` with a set structure and consistent visual style.

- Create new Quarto website project: File -> New Project... -> Quarto Website.
- Preview website to see what we have.
  - Preview page with `Render` button. Use gear button to control how preview works.
  - Render website in `build` tab -> `Render Website`
- Structure: `_quarto.yml`
  - Configuration file (`_quarto.yml`) provides the basic structure of the site.
  - [Navigation](https://quarto.org/docs/websites/website-navigation.html)
    - Top navbar
    - Side navbar
    - Combination of top and side navbar
  - Navigation provides skeleton structure of pages in YAML format. Make sure to use proper whitespace in working in `_quarto.yml`.
- Pages
  - Homepage: `index.qmd`
  - Individual quarto documents turned into web pages
  - Shared YAML in `_quarto.yml` under `format:`. See [HTML Basics](https://quarto.org/docs/output-formats/html-basics.html) for YAML options.
  - Links between pages:
    - `[about](about.qmd)`
    - Section identifier: `# Introduction {#sec-introduction}` and `[about](about.qmd#sec-introduction)`.
  - [Footer](https://quarto.org/docs/websites/website-navigation.html#page-footer): Add a footer to have text at the bottom of each page with `page-footer` in `_quarto.yml`.
- [About page](https://quarto.org/docs/websites/website-about.html): Add an About page with special formatting.
- Aesthetics
	- [Themes](https://quarto.org/docs/output-formats/html-themes.html)
    - Quarto HTML documents are all based on [Bootstrap 5](https://getbootstrap.com/).
	  - Quarto provides access to 25 [Bootswatch themes](https://bootswatch.com/).
	  - Change theme in `_quarto.yml` under `format:`
	- YAML options in `_quarto.yml`
	  - Can make [basic customization](https://quarto.org/docs/output-formats/html-themes.html#basic-options) to the theme in YAML options under `format:`
	- SCSS
	  - Create [fully custom themes](https://quarto.org/docs/output-formats/html-themes.html#custom-themes) with [SASS](https://sass-lang.com) variables through `scss` files, which is a superset of [CSS (Cascading Style Sheets)](https://developer.mozilla.org/en-US/docs/Web/CSS).
	  - `custom.scss`
	  - See [Quarto SASS variables](https://quarto.org/docs/output-formats/html-themes.html#sass-variables) for the most likely variables you might want to change.
	  - See [More About Quarto Themes](https://quarto.org/docs/output-formats/html-themes-more.html) on using Scss.
- [Website tools](https://quarto.org/docs/websites/website-tools.html): Header, footer, and integration with other services.
- [Website search](https://quarto.org/docs/websites/website-search.html): Options for having a search field for website.

## Resources
- The [Quarto documentation](https://quarto.org/docs/guide/) is very good and thorough.
  - [Quarto website documentation](https://quarto.org/docs/websites/)
  - [Quarto blog documentation](https://quarto.org/docs/websites/website-blog.html)
- For an extensive list of resources on Quarto see [Awesome Quarto](https://github.com/mcanouil/awesome-quarto).
- Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund, [*R for Data Science* (2nd Edition)](https://r4ds.hadley.nz): Introduction, Chapters 28 and 29.
- Isabella Velásquez, [Building a blog with Quarto](https://ivelasq.quarto.pub/building-a-blog-with-quarto/).

### Examples of Quarto websites {#sec-ex-sites}
- [Our course website](https://github.com/jessesadler/vt5454-s24)
- [A Rogue Historian by Jesse Sadler](https://www.jessesadler.com)
- [Pipe dreams by Isabella Velásquez](https://ivelasq.rbind.io/)
- [Notes from a data witch by Danielle Navarro](https://blog.djnavarro.net/)
- [Notes from a spreadsheet by Matt Worthington](https://www.mrworthington.com/)
- [The MockUp by Tom Mock](https://themockup.blog/)
- [Maya Gans](https://maya.rbind.io/)
- [Faylab Lab Manual](https://thefaylab.github.io/lab-manual/)
- [Ted Laderas](https://laderast.github.io)
- [Amelia McNamara](https://www.amelia.mn/)
- [Garrick Aden-Buie](https://www.garrickadenbuie.com/)
- [Openscapes](https://openscapes.org/)
